const TOKEN_TYPE = {
  ELEMENT: 'ELEMENT', // 1
  ATTRIBUTE: 2,
  TEXT: 3,
  COMMENT: 8,
  DOCUMENT: 'DOCUMENT', // 9,

  STRING: 'STRING',
  NUMBER: 'NUMBER',
  COMMENT_ML: 'COMMENT_ML',
  COMMENT_SL: 'COMMENT_SL',

  LEFT_CURLY_BRACKET: 'LEFT_CURLY_BRACKET',
  RIGHT_CURLY_BRACKET: 'RIGHT_CURLY_BRACKET',
  EQUAL_SIGN: 'EQUAL_SIGN',
}

module.exports = TOKEN_TYPE
